[[services]]
name = "helpful-flow"
[services.build]
dockerfilePath = "whatsy-backend/Dockerfile"

[[services]]
name = "whatsy-worker"
[services.build]
dockerfilePath = "whatsy-backend/Dockerfile.worker"
