[build]
dockerfilePath = "whatsy-backend/Dockerfile"
buildContext = ".."

[[services]]
name = "helpful-flow"
[services.build]
dockerfilePath = "whatsy-backend/Dockerfile"
buildContext = ".."

[[services]]
name = "whatsy-worker"
[services.build]
dockerfilePath = "whatsy-backend/Dockerfile.worker"
buildContext = ".."
